export default function nameList(){
    return   [
    'Funcionário público do ancapistão', 
    'Eu amo hentai',
    'Daniel Fraga',
    'Servidor Público Libertário',
    'Atropelo comunistas com meu Del Rey',
    'John McAfee Libertário',
    'Xandão, O Lex Luthor do STF',
    'Bovino Gadoso Científico',
    'Desbravador Autêntico',
    'É muito engraçado no final das contas',
    'Eu amo uma oppai bem moreninha',
    'Daniel Fraga Deus do Ancapistão',
    'Libertário mor',
    'Hokage da quinta série',
    'Pikachu Ancap',
    'Peter, minha bisavó está solteira',
    'Espermatozoide Libertário',
    'Tarzão da Mata Atlântica',
    'Neolibertario',
    'Violonista Prateado',
    'Grand Sir Owen Williams, o engenheiro',
    'Ateu com Black Power',
    'Ninguém, eu mesmo sugeri a notícia',
    'Dedo mindinho renegado pelo Lula',
    'Me nota senpai :3',
    'Impressora do Ciro Gomes',
    'Super Hétero Armamentista',
    'Cabeça Livre',
    'Ayn Rand de Minissaia'
    ]
}
